### ISSUE TITLE
Please add Steam login to check library contents

### ISSUE THREAD

**Issue by lietu** [Linaro/works-on-woa#71]
E.g. https://www.protondb.com allows you to log in and see the level of support for your Steam library, without having to manually type in the potentially 1000+ games you may have on Steam alone.

![image](https://github.com/Linaro/works-on-woa/assets/1296558/29d5886e-8e59-4c54-a67f-329a6151f44c)

It would be nice if you could do the same here, log in with Steam and then were able to filter the results with only those in your library. Quick stats of what % of games are at the different tiers of support would be very useful.

**Comment by marcpems** [comment]
Thanks for the suggestion @lietu. No plans to do this at present but I will backlog the idea for a future update.
