### ISSUE TITLE
Sid Meier's Civilization V

### ISSUE THREAD

**Issue by thorr2** [Linaro/works-on-woa#95]
This game crashes on my Surface Pro 11 about 50% of the time when I contact or am contacted by another civilization.  Clicking on their city name contacts them.  When the screen changes to the animation of the foreign leader, it drops to Windows without an error.  You pretty much need to save every turn if you want to make it through a whole game so you can restore from all the crashing.

**Comment by wendyho** [comment]
Hello, please add any game testing results to the form on the contributing page, and we will update the site from the user feedback. Thank you. https://www.worksonwoa.com/contributing#games
